site_name: AutoCampos
site_url: https://caio-lelis.github.io/TPPE-Autocampos-doc/
repo_url: https://github.com/caio-lelis/TPPE-Autocampos-doc

theme:
  name: lux
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest

nav:
  - Início: index.md
  - Arquitetura:
      - Diagramas UML: design/uml.md
      - Arquitetura: design/arquitetura.md
      - Modelo do Banco: design/modelagem_banco.md
  - Desenvolvimento:
      - Guia de Contribuição: desenvolvimento/contribuicao.md
      - Histórias de Usuário: desenvolvimento/historias_usuario.md
      - Arquitetura de Pastas: desenvolvimento/arquitetura_pastas.md
  - Infraestrutura:
      - Docker(Compose): infraestrutura/docker_compose.md
      - Docker(file): infraestrutura/docker_file.md
      - Tecnologias: infraestrutura/tecnologias.md
  - Protótipo:
      - Protótipo Figma: prototipo/prototipo.md
# :::::
# Para rodar deve-se instalar pip install mkdocs-dracula-theme
# pip install pymdown-extensions
# pip install --ignore-installed pymdown-extensions
# https://pawamoy.github.io/mkdocs-gallery/#bootswatch-lux
# <!-- Bootswatch - Lux -->
# <!-- Bootswatch - Solar -->
# <!-- dracula -->

# https://pawamoy.github.io/mkdocs-gallery/#dracula
# pip install mkdocs-bootswatch  